### ISSUE TITLE
m4a tag support & expression in Metadata please

### ISSUE THREAD

**Issue by TMily** [brokkr/poca#107]
i have some podcast publish m4a format file and i want sort my libary via Album by years 
thank you

**Comment by brokkr** [comment]
Hmmm I don't actually know what happens at the moment if I ask to add metadata to m4a. Can you help me with the following:

* The feed of the podcast in question
* The metadata settings you're trying to push
* Any errors thrown by poca (or mention it if it silently ignores your settings)
* The version number of poca

Thanks.

**Comment by TMily** [comment]
RSS:http://www.ximalaya.com/album/203355.xml
settings:
`
<metadata>
        <artist>JokeComing</artist>
        <genre>JokeComing</genre>
        <album>2017</album>
        <albumartist>JokeComing</albumartist>
</metadata>
`
the file will not have any metadata
no errors
install by pip ver1.0

**Comment by brokkr** [comment]
Excellent, thank you. I will have a look at it, see if I can't implement it fairly easily. Mutagen [supports](http://mutagen.readthedocs.io/en/latest/api/mp4.html) it, so I think it should be fairly easy.

**Comment by TMily** [comment]
thanks~~

**Comment by brokkr** [comment]
Technically, it should be there now in the master branch if you want to get at it right away. Be warned though, that I've yet to do any extensive testing or documentation so it's probably pretty buggy :) If you prefer to wait, I'll try to push a 1.1 release this month or the next.

You can see which tags are accepted for mp4s by running `poca-subscribe tags --mp4`. `poca-subscribe tags` now requires an argument, either `--mp3` or `--mp4`.

The supported tags for mp4 are a somwhat small subset of those available for mp3s. This is due to using mutagen's _easy_ mode which translates impossible-to-remember fields names like `TALB` into readable English names such as `album`. Mutagen's developers have put somewhat more effort into supporting this mode for mp3s than for mp4s.

**Comment by TMily** [comment]
thanks and any info of "expression in Metadata"?
like this:
```xml
<metadata>
    <artist>JokeComing</artist>
    <genre>JokeComing</genre>
    <album>
        <year/>.
        <quarterly/>
    </album>
    <albumartist>JokeComing</albumartist>
    <tittle>
        <date/>
        <spisode_tittle/>
    </tittle>
</metadata>
```

**Comment by brokkr** [comment]
Hmmm well I think I see what you're trying to do but none of those things are possible. There are no variables in metadata settings that you can use, only static setttings In other words:

Yes:

    <album>2017</album>

No:

    <album>
        <year/>.
        <quarterly/>
    </album>

As for

    <title>
        <date/>
        <episode_tittle/>
    </title>

Those are the settings for the `rename` feature (also: watch out for typos as poca will skip misspelled tags). When using `rename` you can use the information in the xml feed as variables in the new file name. Those are not available in `metadata`.

Now if you're asking for it as a new feature to be added, I did just start a [new issue](https://github.com/brokkr/poca/issues/110) about that. Still under consideration.
