### ISSUE TITLE
Filename sanitize function should also remove "?" from name

### ISSUE THREAD

**Issue by TobberH** [brokkr/poca#115]
I keep getting an error when poca tries to download a file with a ? in the episode_name

**Comment by brokkr** [comment]
Thanks for the report! Can I ask you for a feed with that for testing purposes?

**Comment by TobberH** [comment]
> Thanks for the report! Can I ask you for a feed with that for testing purposes?

https://arkiv.radio24syv.dk/audiopodcast/channel/16512250

I think it was this one

**Comment by brokkr** [comment]
So I'm obviously too late to test the feed as the site is no longer up. So I'm going to assme that the question here is when using `episode_title` as part of the `rename` block, as question marks in urls is a no-no (see: percent-encoding). In other words: The original filename wouldn't and couldn't have a question mark in it.

Fortunately, I remembered Hey Lesson! which frames all episodes as questions. Here's what I get on Ubuntu 20.04 and an ext4 filesystem using the episode_title to rename:

```
HEY, LESSON!. 6 ➕
 ⇵ 2021-01-27 How do mediums speak to the dead? (The Medium).mp3  [58 Mb]
 ⇵ 2021-02-10 Who invented Chess?.mp3  [59 Mb]
 ⇵ 2021-02-24 How do you design a dream home? (The Sims 4).mp3  [60 Mb]
 ⇵ 2021-03-10 How do you survive in the arctic? (Subnautica Below Zero).mp3  [58 Mb]
 ⇵ 2021-03-24 Why do people like to fight? (Guilty Gear).mp3  [58 Mb]
 ⇵ 2021-04-21 How did sailors become pirates? (Sea of Thieves).mp3  [59 Mb]
```

And an ls -lh of the directory shows we weren't lying:

```
-rw-rw-r-- 1 mads mads  58M May 18 20:33 '2021-01-27 How do mediums speak to the dead? (The Medium).mp3'
-rw-rw-r-- 1 mads mads  59M May 18 20:33 '2021-02-10 Who invented Chess?.mp3'
-rw-rw-r-- 1 mads mads  60M May 18 20:33 '2021-02-24 How do you design a dream home? (The Sims 4).mp3'
-rw-rw-r-- 1 mads mads  59M May 18 20:33 '2021-03-10 How do you survive in the arctic? (Subnautica Below Zero).mp3'
-rw-rw-r-- 1 mads mads  58M May 18 20:33 '2021-03-24 Why do people like to fight? (Guilty Gear).mp3'
-rw-rw-r-- 1 mads mads  59M May 18 20:33 '2021-04-21 How did sailors become pirates? (Sea of Thieves).mp3'
-rw-rw-r-- 1 mads mads 1,9M May 18 20:33  cover.jpg
```

However, not all filesystems are as accomodating as ext4/linux ones. Question marks (and many other characters) are not allowed on NTFS, for one thing. So I'll have a go if I can find a FAT/NTFS USB drive, see if I can reproduce.

**Comment by brokkr** [comment]
Rather than sniffing and trying to figure out what goes and what doesn't globally, I'm thinking a tier system that restricts more with each failure, on a per-download basis. 

1st tier/attempt: Only linux filesystem restrictions (no forward slashes etc.)
2nd tier/attempt: 1st + NTFS/FAT restrictions (no question marks, asterisks etc.)
3rd tier/attempt: Only [a-z], [A-Z], [0-9], hyphens and underscores, using unidecode et al. to degrade as gracefully as possible

It won't perfectly match what is needed but probably get pretty close.

We generate a tuple of three candidate filenames and then - when the download has succeeded - return which one worked out, save that one to poca_filename/poca_abspath. Maybe four, as we might need a fallback should 3rd attempt be reduced to an empty string?

**Comment by brokkr** [comment]
Levels of filesystem accomodation implemented. See https://github.com/brokkr/poca/wiki/Sanitization for details.
