### ISSUE TITLE
Limiting new downloads without deleting old episodes

### ISSUE THREAD

**Issue by diskotechjam** [brokkr/poca#35]
I would prefer to manually delete outdated episodes, however I don't want to download entire feeds. Is it possible to limit the number of new downloads without automatically deleting old episodes?

**Comment by brokkr** [comment]
Let me see if I understand you correctly. 

You would limit the initial intake of episodes to say, the latest episode. Or the 10 latest episodes. Or maybe no episodes at all. Any episodes older than that/thos initial one(s) are never touched. Whenever a new episode comes up, it gets downloaded. No old episodes are deleted automatically so the collection grows as newer episodes are added. Except you would cull outdated episodes yourself. 

Currently the only way to avoid deletions is to give the subscription virtually unlimited space and if the feed has large back catalogue it would mean getting everything. And when you manually delete old episodes the program throws an error because files are missing and quits.

Correct?

The easy thing to do would be to add another mode that delimits the episodes that way. I'm currently testing out a mode that starts from the beginning of the feed. Adding one more shouldn't be that difficult. The manual deletion is where I get a bit wary. Currently missing files is a symptom that something is wrong somewhere. It is possible to change that but I'm not  sure of the implications. 

Can I ask what kind of use this would fit into?

**Comment by brokkr** [comment]
Come to think of it, the first part - the don't-download-old-episodes part - could probably be taken care of as part of the upcoming filter feature. Currently (rev. 178) you can filter on weekday and hour of publication date. Adding the option to filter out all episodes older than XXXX-XX-XX does make sense. 

http://stackoverflow.com/a/8142411

**Comment by brokkr** [comment]
And in the current if you don't set max_mb, poca uses the default which is float('inf') or infinity. Likewise, if you don't set max_no there will be no restrictions on the number of episodes. 

So avoiding having poca delete old episodes is already doable. The remaining question is then if we can deal intelligently with user-deletions.

**Comment by diskotechjam** [comment]
Thanks, I'll check out the filter option as soon as I have a chance.

The main reason I am running into this issue is that I am swtiching over from another podcatcher and already have episodes downloaded. Poca wants to re-downlaod old episodes (which is obviously a waste of time), but i also want to avoid re-downloading episodes I have already deleted.

It would be nice if the date filter could be a global setting to avoid  having to manualy set the filter for each feed. Perhaps there could be a flag option that would automatically updated the global filter to the current date after a complete run. Also, an initial run flag which would limit poca to only downloading the last X number of episodes would be useful for user who already have episodes downloaded, but don't want poca to automatically delete episodes.

**Comment by brokkr** [comment]
Global settings could be useful but they could apply to all metadata, all filters and even settings like max_no and max_mb. Personally, I overwrite genre with 'podcast' on all subscriptions, if only to put proper v2.4 ID3 tags into the files. So to implement it properly it would have to be for all settings other than title and url. And that is a bit of a mouthful - and a separate issue :-) 

First up, I'll see if adding the date-filter can work in principle - and the inclusion of publication date info in the feed is widespread enough to justify it.

**Comment by brokkr** [comment]
Current master (rev197) has the options to:

* filter according to date: Only include episodes later than e.g. 2016-08-18
* setting maximum is optional (i.e. no automatic deletes)
* user deleted files are noted and discounted from future updates

Separately, each one is quite a useful addition, I think, and together they should provide what @diskotechjam asks for. Once I have tried it out in practice for a week or so I'll put out a beta for 0.6. You're more than welcome to help me test either current master or the beta :-)

See https://github.com/brokkr/poca/wiki/Configuration for a configuration guide that includes 0.6 features. 

PLEASE NOTE: Current master (and the beta, and the eventual release) are not compatible with previous releases, so delete old audio files (at least the ones you want poca to be aware of/manage) and your old `$HOME/.poca/db` folder before running an updated version. 

ALSO: The `max_mb` tag is no longer used as it has been superceded by max_number, i.e. limiting the subscription ny number of episodes rather than disk space. This is due to some much needed code simplification. It should in 99% of cases allow for the same level of control. 

FINALLY: It might be advisable to move your old poca.xml to a backup and allow poca to start a fresh one for you to see new features in practice - then bring back the subscriptions and update them to `max_number`.

**Comment by diskotechjam** [comment]
I've been using the beta for a couple days now and everything seems to be working great. This is exavtly what I needed to complete the transition from my other podcatcher. The episode deleted by user notification is a nice touch. Overall, poca seems to be very stable and reliable. 
Nice work, thanks!

**Comment by brokkr** [comment]
Glad to hear it and thanks for the testing and feedback :-) I'm closing the issue and pushing 0.6.
